* clingo-mode

A major mode for editing [[https://potassco.org/][Potassco]] Answer Set Programs files (~.lp~).

From the Potassco website:  
#+begin_quote
Answer Set Programming (ASP) offers a simple and powerful modeling language to solve combinatorial problems. With our tools you can concentrate on an actual problem, rather than a smart way of implementing it.
#+end_quote

** Features

- Syntax highlighting
- Commenting functionality
- Run clingo from emacs
- Some smart indentation (inherited from parent prolog-mode)

*** Keybindings

- ~C-c C-b~ Call clingo with the current buffer
- ~C-c C-e~ Call clingo with the current buffer as encoding and some user provided instance
- ~C-c C-r~ Call clingo with the currently selected region

The above will all prompt for clingo command-line options (e.g., ~-c n=3 -n 0~, etc.).

- ~C-c C-c~ Comment region
- ~C-c C-u~ Uncomment region

** Installation

*** Melpa

~clingo-mode~ is available through the [[MELPA][https://github.com/melpa/melpa]] repository.
This is the recommended way to install.

You can either install ~clingo-mode~ by hand with:

#+begin_src lisp
M-x package-install [RET] clingo-mode [RET]
#+end_src

or place the following snippet into your Emacs init file:

#+begin_src lisp
(unless (package-installed-p 'clingo-mode)
  (package-refresh-contents)
  (package-install 'clingo-mode))
#+end_src

*** Manually

Download the ~clingo-mode.el~ file from this repository.
Either put it into your emacs load path and call ~(require 'clingo-mode)~ 
in your init file or load it directly with ~(load "~/path/to/clingo-mode.el")~

Afterwards opening an ~.lp~ file triggers ~clingo-mode~ or
call ~M-x clingo-mode~ within an open asp file.

** todo

- Smart indentation based on nesting depth
- Refactoring of predicates/variables (complete buffer and #program parts)
- Color compilation output
- Smart rearrange of compilation output (predicates separated, table...) 
- yas-snippet for rules; constraints; soft constraints; generation?
- sync as much as possible with [[https://github.com/rkaminsk/vim-syntax-clingo][vim-syntax-clingo]]
- integrations with org-mode, company, etc.

** Contributions

Contributions, via issues, ideas and pull requests, are very welcome!

** License

Copyright (c) 2020 by Ivan Uemlianin \\
Copyright (c) 2017 by Henrik Jürges

Distributed under the [[http://www.gnu.org/licenses/gpl-3.0.html][GNU General Public License v3]]; see [[LICENSE.md][LICENSE]] or type ~C-h C-c~ to view it.
